import { createServer } from 'vite';
import { build } from 'esbuild';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
await build({entryPoints:['electron/main.ts'],bundle:true,platform:'node',format:'esm',target:'node22',outfile:'dist-electron/main.mjs',external:['electron','music-metadata']});
await build({entryPoints:['electron/preload.ts'],bundle:true,platform:'node',format:'cjs',target:'node22',outfile:'dist-electron/preload.cjs',external:['electron']});
const server=await createServer();await server.listen();
const env={...process.env,LUMA_DEV_URL:'http://127.0.0.1:5173/'};delete env.ELECTRON_RUN_AS_NODE;
const child=spawn(createRequire(import.meta.url)('electron'),['.'],{stdio:'inherit',env});
child.on('exit',async code=>{await server.close();process.exit(code??0);});
process.on('SIGINT',()=>child.kill());
