import { _electron as electron } from '@playwright/test';
import { createRequire } from 'node:module';
import { mkdtemp, mkdir, writeFile, readFile, rm, access, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';

const require=createRequire(import.meta.url);
const root=process.cwd();
const selectionModifier=process.platform==='darwin'?'Meta':'Control';
const dir=await mkdtemp(path.join(tmpdir(),'sono-drop-'));
const data=path.join(dir,'data');
const folder=path.join(dir,'음악 폴더');
await mkdir(data);await mkdir(path.join(folder,'하위 폴더'),{recursive:true});
await mkdir('test-results',{recursive:true});
function wave(){
  const size=44100*2*12;const b=Buffer.alloc(44+size);
  b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);
  b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(44100,24);b.writeUInt32LE(88200,28);
  b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);
  return b;
}
const files=[path.join(dir,'드롭 음악 A.wav'),path.join(dir,'드롭 음악 B.wav')];
const nested=path.join(folder,'하위 폴더','폴더 음악 C.wav');
const rootSong=path.join(folder,'루트 음악 D.wav');
const sibling=path.join(folder,'다른 폴더','폴더 음악 E.wav');
await mkdir(path.dirname(sibling));
const unsupported=path.join(dir,'메모.txt');
for(const file of [...files,nested,rootSong,sibling])await writeFile(file,wave());
await writeFile(unsupported,'not music');
const env={...process.env,LUMA_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;delete env.LUMA_DEV_URL;
const packaged=process.argv.includes('--packaged');
const launchOptions={executablePath:packaged?path.join(root,'release','win-unpacked','SONO.exe'):require('electron'),args:packaged?[]:[root],env};
let application=await electron.launch(launchOptions);
let page;
try{
  page=await application.firstWindow();page.setDefaultTimeout(7000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.getByRole('heading',{name:'내 음악.'}).waitFor();
  const cdp=await application.context().newCDPSession(page);
  async function drag(paths,type='drop',target='.topbar'){
    const box=await page.locator(target).first().boundingBox();
    const params={x:box.x+box.width/2,y:box.y+box.height/2,data:{items:[],files:paths,dragOperationsMask:1}};
    await cdp.send('Input.dispatchDragEvent',{...params,type:'dragEnter'});
    await cdp.send('Input.dispatchDragEvent',{...params,type:'dragOver'});
    if(type==='drop')await cdp.send('Input.dispatchDragEvent',{...params,type:'drop'});
    else {
      await cdp.send('Input.dispatchDragEvent',{...params,type:'dragOver',x:-10,y:-10});
      await cdp.send('Input.dispatchDragEvent',{...params,type:'dragCancel'});
    }
  }
  await drag(files);
  await page.getByRole('button',{name:'드롭 음악 A',exact:true}).waitFor();
  await page.getByRole('button',{name:'드롭 음악 B',exact:true}).waitFor();
  assert.equal(await page.getByRole('row').count(),3);
  console.log('PASS native-backed multiple file drop');
  await drag(files,'drop','.sidebar');
  await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('0곡'));
  assert.equal(await page.getByRole('row').count(),3);
  console.log('PASS sidebar drop and duplicate protection');
  await drag([folder]);
  await page.getByRole('button',{name:'폴더 음악 C',exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'내 음악.'}).count(),1);
  assert.equal(await page.getByRole('navigation',{name:'음악 폴더'}).count(),0);
  assert.equal(await page.getByRole('row').count(),6);
  assert.equal(await page.locator('.folder-group-heading').count(),4);
  const groups=await page.locator('.track-table').evaluate(el=>{
    const result=[];let group;
    for(const child of el.children){if(child.classList.contains('folder-group-heading')){group={folder:child.textContent,titles:[]};result.push(group);}else if(child.querySelector('.track-title'))group?.titles.push(child.querySelector('.track-title').textContent);}
    return result;
  });
  assert.deepEqual(groups.find(g=>g.folder.includes('하위 폴더')).titles,['폴더 음악 C']);
  assert.deepEqual(groups.find(g=>g.folder.includes('다른 폴더')).titles,['폴더 음악 E']);
  assert.equal(await page.locator('.track-title-toggle').count(),0);
  assert.equal(await page.getByRole('button',{name:'폴더 음악 C 재생',exact:true}).evaluate(el=>el.classList.contains('track-number')),true);
  await page.getByRole('button',{name:'페이드 설정',exact:true}).click();
  await page.getByRole('slider',{name:'페이드 인 시간'}).fill('1');
  await page.getByRole('slider',{name:'페이드 아웃 시간'}).fill('1');
  await page.screenshot({path:'test-results/SONO-fade.png'});
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.evaluate(()=>{
    window.audioGains=[];const create=AudioContext.prototype.createGain;
    AudioContext.prototype.createGain=function(){const gain=create.call(this);window.audioGains.push(gain);return gain;};
  });
  await page.getByRole('button',{name:'폴더 음악 C 재생',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('audio').currentTime>0.1);
  const fadeIn=await page.evaluate(()=>window.audioGains.at(-1).gain.value);
  assert.ok(fadeIn>0&&fadeIn<0.9,'fade-in must ramp the actual Web Audio gain');
  await page.waitForFunction(()=>document.querySelector('audio').currentTime>0.4);
  await page.waitForFunction(()=>window.audioGains.at(-1).gain.value>0.98);
  await page.getByRole('button',{name:'폴더 음악 C 일시정지',exact:true}).click();
  await page.waitForTimeout(200);
  const fadeOut=await page.evaluate(()=>({gain:window.audioGains.at(-1).gain.value,paused:document.querySelector('audio').paused}));
  assert.ok(fadeOut.gain>0&&fadeOut.gain<0.95);assert.equal(fadeOut.paused,false);
  await page.getByRole('button',{name:'폴더 음악 C 재생',exact:true}).click();
  await page.waitForTimeout(1100);
  assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),false,'resuming during fade-out must cancel the delayed pause');
  await page.getByRole('button',{name:'폴더 음악 C 일시정지',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('audio').paused);
  await page.getByRole('slider',{name:'재생 위치'}).fill('4');
  const paused=await page.evaluate(()=>document.querySelector('audio').currentTime);
  await page.getByRole('button',{name:'폴더 음악 C 재생',exact:true}).click();
  assert.ok(await page.evaluate(()=>document.querySelector('audio').currentTime)>=paused-0.05,'left play must resume without restarting');
  await page.waitForFunction(time=>!document.querySelector('audio').paused&&document.querySelector('audio').currentTime>time,paused);
  await page.getByRole('button',{name:'폴더 음악 C 일시정지',exact:true}).click();
  await page.getByRole('button',{name:'폴더 음악 C 좋아요',exact:true}).click();
  console.log('PASS actual Web Audio fade in/out and paused seek resume');
  await page.waitForFunction(()=>document.querySelector('audio').paused);
  await page.getByRole('button',{name:'폴더 음악 C 재생',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('audio').paused);
  await page.getByRole('button',{name:'루트 음악 D 재생',exact:true}).click();
  await page.getByRole('button',{name:'루트 음악 D 일시정지',exact:true}).click();
  const nextId=await page.evaluate(async()=>{const {state}=await window.luma.getState();return state.tracks.find(t=>t.title==='루트 음악 D').id;});
  await page.waitForFunction(id=>document.querySelector('audio').paused&&document.querySelector('audio').src===`luma://audio/${id}`,nextId);
  await page.getByRole('button',{name:'루트 음악 D 재생',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('audio').paused&&document.querySelector('audio').currentTime>0.1);
  assert.equal(await page.evaluate(()=>document.querySelector('audio').src),`luma://audio/${nextId}`);
  await page.getByRole('button',{name:'루트 음악 D 일시정지',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('audio').paused);
  console.log('PASS pausing during a fading song change retains the newly selected source');
  await page.screenshot({path:'test-results/SONO-folders.png'});
  await page.setViewportSize({width:960,height:650});
  const bottom=await page.locator('.sidebar-bottom').boundingBox();
  const player=await page.locator('.player-bar').boundingBox();
  assert.ok(bottom.y+bottom.height<=player.y+1,'sidebar controls must fit above the player');
  await page.screenshot({path:'test-results/SONO-folders-compact.png'});
  assert.equal(await page.locator('.collection-tracks').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.setViewportSize({width:1320,height:880});
  await application.evaluate(({dialog},filePaths)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths});},[folder]);
  await page.getByRole('button',{name:'음악 추가',exact:true}).click();
  await page.getByRole('button',{name:'폴더 가져오기',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('0곡'));
  assert.equal(await page.getByRole('row').count(),6);
  await page.getByRole('button',{name:'폴더 음악 C 좋아요 취소',exact:true}).waitFor();
  const before=await page.locator('.track-title').allTextContents();
  const rows=page.locator('.track-row[draggable="true"]');
  const source=rows.filter({has:page.getByRole('button',{name:before[1],exact:true})});
  const target=rows.filter({has:page.getByRole('button',{name:before[0],exact:true})});
  await source.locator('.drag-handle').dragTo(target.locator('.drag-handle'),{targetPosition:{x:8,y:3}});
  let reordered=await page.locator('.track-title').allTextContents();
  assert.equal(reordered[0],before[1]);assert.equal(reordered[1],before[0]);
  assert.equal(await page.getByRole('row').count(),6);
  console.log('PASS inline folder groups, single left play/pause/resume, and song reordering');
  const m3u=path.join(dir,'드래그 목록.m3u8');await writeFile(m3u,[...files,nested].join('\n'));
  await application.evaluate(({dialog},filePaths)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths});},[m3u]);
  await page.getByRole('button',{name:'음악 추가',exact:true}).click();
  await page.getByRole('button',{name:'M3U 목록 가져오기',exact:true}).click();
  await page.getByRole('button',{name:'드래그 목록 3',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.track-title').length===3);
  await page.locator('.track-row .drag-handle').last().dragTo(page.locator('.track-row .drag-handle').first(),{targetPosition:{x:8,y:3}});
  await page.waitForFunction(()=>document.querySelector('.track-title')?.textContent==='폴더 음악 C');
  assert.deepEqual(await page.locator('.track-title').allTextContents(),['폴더 음악 C','드롭 음악 A','드롭 음악 B']);
  await page.getByRole('button',{name:'드롭 음악 A',exact:true}).click();
  await page.getByRole('button',{name:'드롭 음악 B',exact:true}).click({modifiers:['Shift']});
  await page.screenshot({path:'test-results/SONO-selection.png'});
  await page.getByRole('button',{name:'선택 삭제 (2)',exact:true}).click();
  assert.deepEqual(await page.locator('.track-title').allTextContents(),['폴더 음악 C']);
  await page.getByRole('button',{name:'내 음악',exact:false}).first().click();
  assert.deepEqual(await page.locator('.track-title').allTextContents(),reordered);
  console.log('PASS playlist drag reordering across folders');
  const oldFolders=await page.locator('.folder-group-heading strong').allTextContents();
  const folderSource=page.locator('.folder-group-heading').last().locator('.folder-drag-handle');
  const folderTarget=page.locator('.folder-group-heading').first();
  await folderSource.scrollIntoViewIfNeeded();const sourceBox=await folderSource.boundingBox();
  await page.mouse.move(sourceBox.x+10,sourceBox.y+10);await page.mouse.down();
  await page.mouse.move(sourceBox.x+45,sourceBox.y+10,{steps:5});
  await folderTarget.scrollIntoViewIfNeeded();const targetBox=await folderTarget.boundingBox();
  await page.mouse.move(targetBox.x+100,targetBox.y+targetBox.height-5,{steps:10});await page.mouse.up();
  const newFolders=await page.locator('.folder-group-heading strong').allTextContents();
  assert.equal(newFolders[0],oldFolders.at(-1));
  const cancelledSource=page.locator('.folder-group-heading').first().locator('.folder-drag-handle');
  await cancelledSource.scrollIntoViewIfNeeded();const cancelBox=await cancelledSource.boundingBox();
  await page.mouse.move(cancelBox.x+10,cancelBox.y+10);await page.mouse.down();
  await page.mouse.move(cancelBox.x+45,cancelBox.y+10,{steps:5});await page.keyboard.press('Escape');await page.mouse.up();
  await page.waitForFunction(()=>!document.querySelector('.selection-toolbar.accepting-drop'));
  await drag(files,'drop','.folder-group-heading');
  await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('0곡'));
  assert.equal(await page.getByRole('row').count(),6);
  reordered=await page.locator('.track-title').allTextContents();
  console.log('PASS folder block reordering and playlist bulk removal');
  const url=page.url();await drag([unsupported]);
  await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('음악 파일이 없습니다'));
  assert.equal(page.url(),url);assert.equal(await page.getByRole('row').count(),6);
  console.log('PASS unsupported drop feedback and navigation protection');
  await drag(files,'cancel');
  await page.locator('.drop-overlay').waitFor({state:'hidden'});
  // Keep a native drag hovering long enough to capture the drop guidance.
  const box=await page.locator('.content').boundingBox();
  const params={x:box.x+box.width/2,y:box.y+box.height/2,data:{items:[],files,dragOperationsMask:1}};
  await cdp.send('Input.dispatchDragEvent',{...params,type:'dragEnter'});
  await cdp.send('Input.dispatchDragEvent',{...params,type:'dragOver'});
  await page.locator('.drop-overlay').waitFor();
  await page.screenshot({path:'test-results/SONO-drop.png'});
  await cdp.send('Input.dispatchDragEvent',{...params,type:'dragOver',x:-10,y:-10});
  await cdp.send('Input.dispatchDragEvent',{...params,type:'dragCancel'});
  await page.locator('.drop-overlay').waitFor({state:'hidden'});
  console.log('PASS drop guidance and leaving the window');
  assert.deepEqual(errors,[]);
  await application.close();
  const saved=JSON.parse(await readFile(path.join(data,'state.json'),'utf8'));
  assert.equal(saved.tracks.length,5);
  assert.equal(saved.tracks.find(t=>t.title==='폴더 음악 C').folderRoot,await realpath(folder));
  application=await electron.launch(launchOptions);
  page=await application.firstWindow();page.on('pageerror',error=>errors.push(error.message));
  await page.getByRole('heading',{name:'내 음악.'}).waitFor();
  assert.equal(await page.getByRole('row').count(),6);
  assert.equal(await page.locator('.folder-group-heading').count(),4);
  assert.deepEqual(await page.locator('.track-title').allTextContents(),reordered);
  await page.getByRole('button',{name:'폴더 음악 C 좋아요 취소',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);
  assert.deepEqual(errors,[]);
  console.log('PASS reimport favorites, compact layout, and restart folder/order persistence');
  await page.getByRole('button',{name:'페이드 설정',exact:true}).click();
  assert.equal(await page.getByRole('slider',{name:'페이드 인 시간'}).inputValue(),'1');
  assert.equal(await page.getByRole('slider',{name:'페이드 아웃 시간'}).inputValue(),'1');
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.getByRole('button',{name:'드롭 음악 A',exact:true}).click();
  await page.getByRole('button',{name:'드롭 음악 B',exact:true}).click({modifiers:['Shift']});
  await page.getByRole('button',{name:'선택 삭제 (2)',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.track-title').length===3);
  assert.equal(await page.getByRole('button',{name:'드롭 음악 A',exact:true}).count(),0);
  for(const file of [...files,nested,rootSong,sibling])await access(file);
  await page.keyboard.press(`${selectionModifier}+a`);
  await page.getByRole('button',{name:'선택 삭제 (3)',exact:true}).waitFor();
  await page.keyboard.press('Delete');
  await page.getByRole('button',{name:'첫 음악 가져오기',exact:true}).waitFor();
  await application.close();
  const deleted=JSON.parse(await readFile(path.join(data,'state.json'),'utf8'));
  assert.equal(deleted.tracks.length,0);assert.equal(deleted.playlists[0].trackIds.length,0);assert.equal(deleted.playback.currentId,null);
  for(const file of [...files,nested,rootSong,sibling])await access(file);
  application=await electron.launch(launchOptions);page=await application.firstWindow();
  await page.getByRole('button',{name:'첫 음악 가져오기',exact:true}).waitFor();
  console.log('PASS bulk library deletion, select all, saved removal, and original files retained');
  console.log('PASS imported tracks persisted and no renderer exceptions');
}catch(error){await page?.screenshot({path:'test-results/drop-failure.png'}).catch(()=>{});throw error;}
finally{await application.close().catch(()=>{});await rm(dir,{recursive:true,force:true});}
