import { _electron as electron } from '@playwright/test';
import { createRequire } from 'node:module';
import { mkdtemp,mkdir,writeFile,readFile,rm,realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const require=createRequire(import.meta.url),root=process.cwd(),dir=await realpath(await mkdtemp(path.join(tmpdir(),'sono-loop-'))),data=path.join(dir,'data');await mkdir(data);await mkdir('test-results',{recursive:true});
function wave(){const rate=16000,size=rate*2*12,b=Buffer.alloc(44+size);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);for(let i=0;i<size/2;i++)b.writeInt16LE(Math.round(Math.sin(i/rate*440*Math.PI*2)*(i<rate*6?.2:.8)*32767),44+i*2);return b;}
const files=['A','B'].map(name=>path.join(dir,`${name}.wav`));for(const file of files)await writeFile(file,wave());const digest=async file=>createHash('sha256').update(await readFile(file)).digest('hex'),original=await Promise.all(files.map(digest));
const env={...process.env,LUMA_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;delete env.LUMA_DEV_URL;const executable=process.env.SONO_SMOKE_EXECUTABLE,options={executablePath:executable||require('electron'),args:executable?[]:[root],env};
let app,page;const errors=[],button=name=>page.getByRole('button',{name,exact:true}),modal=()=>page.getByRole('dialog',{name:'구간 반복 (A–B)',exact:true}),seek=()=>page.getByRole('slider',{name:'재생 위치'});
async function launch(){app=await electron.launch(options);page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'내 음악.'}).waitFor();}
async function edit(a,b){await button('구간 반복').click();await modal().getByRole('textbox',{name:'A 시작 시간'}).fill(a);await modal().getByRole('textbox',{name:'B 종료 시간'}).fill(b);}
async function apply(){await modal().getByRole('button',{name:'적용',exact:true}).click();assert.equal(await button('구간 반복').getAttribute('aria-pressed'),'true');}
async function paused(){await page.waitForFunction(()=>document.querySelector('audio').paused);}
async function mode(name){await page.getByRole('button',{name:/^재생 방식:/}).click();await page.getByRole('radio',{name,exact:true}).check();await button('닫기').click();}
async function monitor(){await page.evaluate(()=>{window.loopFrames=[];window.loopReturns=0;let previous=document.querySelector('audio').currentTime;window.loopMonitor=setInterval(()=>{const audio=document.querySelector('audio'),time=audio.currentTime;if(!audio.paused){if(previous-time>.35)window.loopReturns++;window.loopFrames.push({time,gain:window.audioGains.at(-1)?.gain.value});}previous=time;},15);});}
async function stopMonitor(){return page.evaluate(()=>{clearInterval(window.loopMonitor);return {frames:window.loopFrames,returns:window.loopReturns};});}
try{
  await launch();assert.equal(await button('구간 반복').isDisabled(),true);await page.evaluate(()=>{const original=AudioContext.prototype.createGain;window.audioGains=[];AudioContext.prototype.createGain=function(...args){const gain=original.apply(this,args);window.audioGains.push(gain);return gain;};});
  await app.evaluate(({dialog},files)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:files});},files);await button('첫 음악 가져오기').click();await button('B').waitFor();await button('A 재생').click();await page.waitForFunction(()=>document.querySelector('audio').currentTime>.1);await button('A 일시정지').click();await paused();if(await button('알림 닫기').count())await button('알림 닫기').click();
  await edit('4','2');assert.equal(await modal().getByRole('button',{name:'적용'}).isDisabled(),true);await modal().getByRole('textbox',{name:'A 시작 시간'}).fill('2');await modal().getByRole('textbox',{name:'B 종료 시간'}).fill('2.05');assert.equal(await modal().getByRole('button',{name:'적용'}).isDisabled(),true);await modal().getByRole('textbox',{name:'B 종료 시간'}).fill('13');assert.equal(await modal().getByRole('button',{name:'적용'}).isDisabled(),true);await modal().getByRole('textbox',{name:'B 종료 시간'}).fill('2.75');
  await page.setViewportSize({width:960,height:650});await page.screenshot({path:'test-results/SONO-loop-dialog.png'});await apply();assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),2);await page.getByRole('img',{name:'구간 반복 A 0:02 B 0:02.75',exact:true}).waitFor();
  await seek().fill('0');assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),2);await seek().fill('10');assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),2.75);
  console.log('PASS A/B direct input, ordering/minimum/out-of-range validation, visible markers, bounded seeking, compact dialog and paused state');
  await button('B 더 보기').click();await button('대기열에 추가').click();const bid=(await page.evaluate(()=>window.luma.getState())).state.tracks.find(t=>t.title==='B').id;
  await button('A 재생').click();await monitor();await page.waitForFunction(()=>window.loopReturns>=4);const measure=await stopMonitor();assert.ok(measure.frames.every(f=>f.time>=1.98&&f.time<=2.80));assert.ok(measure.frames.slice(Math.floor(measure.frames.length/2)).every(f=>f.gain>.95));assert.equal(await page.locator('.now-playing strong').textContent(),'A');assert.deepEqual((await page.evaluate(()=>window.luma.getState())).state.playback.queue,[bid]);await page.locator('.player-bar').screenshot({path:'test-results/SONO-loop-player.png'});
  console.log('PASS actual PCM playback repeatedly returns from B to A without advancing queued audio or fading out at the loop boundary');
  await button('A 일시정지').click();await paused();const position=await page.evaluate(()=>document.querySelector('audio').currentTime);await page.waitForTimeout(1100);assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),position);await button('A 재생').click();await page.waitForFunction(()=>!document.querySelector('audio').paused&&document.querySelector('audio').currentTime>=2&&document.querySelector('audio').currentTime<=2.8);
  await mode('현재 곡만 재생 후 정지');await monitor();await page.waitForFunction(()=>window.loopReturns>=2);await stopMonitor();assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),false);await button('구간 반복').click();await modal().getByRole('button',{name:'구간 반복 해제'}).click();assert.equal(await button('구간 반복').getAttribute('aria-pressed'),'false');await seek().fill('11.95');await paused();assert.equal(await page.locator('.now-playing strong').textContent(),'A');assert.deepEqual((await page.evaluate(()=>window.luma.getState())).state.playback.queue,[bid]);
  console.log('PASS pause/resume, A/B precedence over stop-after-current, and clearing restores the saved playback mode and preserves the queue');
  await edit('10.5','12');await apply();await button('A 재생').click();await monitor();await page.waitForFunction(()=>window.loopReturns>=3);const tail=await stopMonitor();assert.ok(tail.frames.every(f=>f.time>=10.48&&f.time<=12.01));assert.equal(await page.locator('.now-playing strong').textContent(),'A');await button('다음 곡').click();await page.waitForFunction(()=>document.querySelector('.now-playing strong').textContent==='B'&&!document.querySelector('audio').paused);assert.equal(await button('구간 반복').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.waveform-loop-region').count(),0);
  console.log('PASS B at the physical file end repeats correctly; manual next clears A/B and plays the queued song');
  await button('A 재생').click();await page.waitForFunction(()=>document.querySelector('.now-playing strong').textContent==='A'&&document.querySelector('audio').currentTime<2);await button('A 일시정지').click();await paused();
  await button('음원 길이 조정').click();let trim=page.getByRole('dialog',{name:'음원 길이 조정',exact:true});await trim.getByRole('textbox',{name:'시작 시간'}).fill('2');await trim.getByRole('textbox',{name:'종료 시간'}).fill('8');await trim.getByRole('button',{name:'적용'}).click();await edit('1','2');await apply();assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),3);await seek().fill('7');assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),4);await page.getByRole('img',{name:'구간 반복 A 0:01 B 0:02',exact:true}).waitFor();
  await button('음원 길이 조정').click();trim=page.getByRole('dialog',{name:'음원 길이 조정',exact:true});await trim.getByRole('textbox',{name:'시작 시간'}).fill('3');await trim.getByRole('textbox',{name:'종료 시간'}).fill('9');await trim.getByRole('button',{name:'적용'}).click();assert.equal(await button('구간 반복').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);
  await seek().fill('4.5');await button('구간 반복').click();await modal().getByRole('button',{name:'현재 위치를 A로'}).click();assert.equal(await modal().getByRole('textbox',{name:'A 시작 시간'}).inputValue(),'0:01.5');await modal().getByRole('button',{name:'취소'}).click();await seek().fill('5.5');await button('구간 반복').click();await modal().getByRole('textbox',{name:'A 시작 시간'}).fill('1.5');await modal().getByRole('button',{name:'현재 위치를 B로'}).click();assert.equal(await modal().getByRole('textbox',{name:'B 종료 시간'}).inputValue(),'0:02.5');await apply();
  console.log('PASS trimmed-source relative A/B times, current-position shortcuts, cancellation, and trim edits clear the loop without autoplay');
  await app.close();app=undefined;await launch();assert.equal(await button('구간 반복').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);assert.deepEqual((await page.evaluate(()=>window.luma.getState())).state.tracks.find(t=>t.title==='A').trim,{start:3,end:9});assert.deepEqual(await Promise.all(files.map(digest)),original);assert.deepEqual(errors,[]);
  console.log('PASS restart leaves A/B off while preserving original clip/settings; original audio hashes unchanged and no renderer errors');
}finally{if(app)await app.close();await rm(dir,{recursive:true,force:true});}
