import { _electron as electron } from '@playwright/test';
import { createRequire } from 'node:module';
import { mkdtemp,mkdir,writeFile,readFile,rm,realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const require=createRequire(import.meta.url),root=process.cwd(),dir=await realpath(await mkdtemp(path.join(tmpdir(),'sono-trim-'))),data=path.join(dir,'data');await mkdir(data);await mkdir('test-results',{recursive:true});
function wave(){const rate=16000,size=rate*2*12,b=Buffer.alloc(44+size);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);for(let i=0;i<size/2;i++)b.writeInt16LE(Math.round(Math.sin(i/rate*440*Math.PI*2)*(i<rate*6?.2:.8)*32767),44+i*2);return b;}
const files=['A','B'].map(name=>path.join(dir,`${name}.wav`));for(const file of files)await writeFile(file,wave());const digest=async file=>createHash('sha256').update(await readFile(file)).digest('hex');const before=await Promise.all(files.map(digest));
const env={...process.env,LUMA_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;delete env.LUMA_DEV_URL;const executable=process.env.SONO_SMOKE_EXECUTABLE,options={executablePath:executable||require('electron'),args:executable?[]:[root],env};
let app,page;const errors=[];const button=name=>page.getByRole('button',{name,exact:true});const modal=()=>page.getByRole('dialog',{name:'음원 길이 조정',exact:true});
async function launch(){app=await electron.launch(options);page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'내 음악.'}).waitFor();}
async function edit(name,start,end){await button(`${name} 더 보기`).click();await page.locator('.track-dropdown').getByRole('button',{name:'음원 길이 조정',exact:true}).click();await modal().getByRole('textbox',{name:'시작 시간'}).fill(start);await modal().getByRole('textbox',{name:'종료 시간'}).fill(end);}
async function mode(name){await page.getByRole('button',{name:/^재생 방식:/}).click();await page.getByRole('radio',{name,exact:true}).check();await button('닫기').click();}
async function saved(range){await page.waitForFunction(async range=>{const t=(await window.luma.getState()).state.tracks.find(t=>t.title==='A');return range?t?.trim?.start===range.start&&t.trim.end===range.end:!t?.trim;},range);}
try{
  await launch();await app.evaluate(({dialog},files)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:files});},files);await button('첫 음악 가져오기').click();await button('B').waitFor();await page.getByRole('combobox',{name:'음악 정렬'}).selectOption('title');
  if(await button('알림 닫기').count())await button('알림 닫기').click();
  await edit('A','8','2');assert.equal(await modal().getByRole('button',{name:'적용',exact:true}).isDisabled(),true);await modal().getByRole('textbox',{name:'시작 시간'}).fill('2');await modal().getByRole('textbox',{name:'종료 시간'}).fill('6');await modal().getByRole('slider',{name:'시작 지점'}).fill('2.25');assert.equal(await modal().getByRole('textbox',{name:'시작 시간'}).inputValue(),'0:02.25');await modal().getByRole('textbox',{name:'시작 시간'}).fill('2');
  await page.setViewportSize({width:960,height:650});await page.screenshot({path:'test-results/SONO-trim-dialog.png'});await modal().getByRole('button',{name:'적용',exact:true}).click();await saved({start:2,end:6});
  assert.equal((await page.locator('.track-row').filter({has:button('A')}).locator('.track-duration').textContent()).trim(),'0:04');console.log('PASS invalid range protection, precise time/slider editing, trimmed list duration and compact dialog');
  await button('A 재생').click();await page.waitForFunction(()=>!document.querySelector('audio').paused&&document.querySelector('audio').currentTime>=2);const seek=page.getByRole('slider',{name:'재생 위치'});assert.equal(await seek.getAttribute('min'),'2');assert.equal(await seek.getAttribute('max'),'6');await seek.fill('4');await page.getByRole('img',{name:'음원 파형',exact:true}).waitFor();await page.locator('.player-bar').screenshot({path:'test-results/SONO-trim-player.png'});assert.ok(await page.evaluate(()=>document.querySelector('audio').currentTime)>=4);
  await seek.fill('5.95');await page.waitForFunction(()=>document.querySelector('.now-playing strong').textContent==='B'&&!document.querySelector('audio').paused);console.log('PASS actual trimmed start/seek/end and automatic next, cropped real waveform');
  await mode('한 곡 반복');await button('A 재생').click();await page.waitForFunction(()=>document.querySelector('audio').currentTime>=2&&document.querySelector('audio').currentTime<3);await seek.fill('5.95');await page.waitForFunction(()=>document.querySelector('audio').currentTime>=2&&document.querySelector('audio').currentTime<3&&!document.querySelector('audio').paused);assert.equal(await page.locator('.now-playing strong').textContent(),'A');console.log('PASS repeat starts at the trimmed start and never plays the excluded tail');
  await mode('현재 곡만 재생 후 정지');await seek.fill('5.95');await page.waitForFunction(()=>document.querySelector('audio').paused);assert.equal(await page.locator('.now-playing strong').textContent(),'A');await button('음원 길이 조정').click();await modal().getByRole('textbox',{name:'시작 시간'}).fill('3');await modal().getByRole('textbox',{name:'종료 시간'}).fill('7');await modal().getByRole('button',{name:'적용',exact:true}).click();await saved({start:3,end:7});assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);assert.equal(await page.evaluate(()=>document.querySelector('audio').currentTime),3);console.log('PASS stop-after-current at trimmed end and live paused edits without autoplay');
  await seek.fill('4');await button('음원 길이 조정').click();await modal().getByRole('button',{name:'현재 위치를 시작으로'}).click();assert.equal(await modal().getByRole('textbox',{name:'시작 시간'}).inputValue(),'0:04');await modal().getByRole('button',{name:'취소',exact:true}).click();await saved({start:3,end:7});
  await button('음악 추가').click();await button('파일 가져오기').click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('0곡'));await saved({start:3,end:7});
  await app.close();app=undefined;await launch();assert.equal(await page.evaluate(()=>document.querySelector('audio').paused),true);await saved({start:3,end:7});assert.equal(await page.getByRole('slider',{name:'재생 위치'}).getAttribute('min'),'3');console.log('PASS current-position shortcut, cancellation, duplicate import and saved range after restart');
  await button('음원 길이 조정').click();await modal().getByRole('button',{name:'원래 길이',exact:true}).click();await modal().getByRole('button',{name:'적용',exact:true}).click();await saved(null);assert.equal(await page.getByRole('slider',{name:'재생 위치'}).getAttribute('min'),'0');assert.equal(await page.getByRole('slider',{name:'재생 위치'}).getAttribute('max'),'12');assert.deepEqual(await Promise.all(files.map(digest)),before);assert.deepEqual(errors,[]);console.log('PASS restore original length, original file hashes unchanged, no renderer errors');
}finally{if(app)await app.close();await rm(dir,{recursive:true,force:true});}
